#define COMMAND_BYTE 0x00
#define COMMAND_HEARTBEAT	0x01
#define COMMAND_SETACCELERATION	0x02
#define COMMAND_GOPOSITION	0x03
#define COMMAND_REPORTENCODER 0x10
#define COMMAND_REPORTSTANDBY 0x11

#define COMMAND_SETACCELERATION_LENGTH 8